export const data = [
  {
    name: "Unilorin Dam",
    type: "resort",
    images: [
      require("./assets/Outside/unilorin dam.jpeg"),
      require("./assets/Outside/unilorin.dam.jpeg"),
    ],
    imagesPath: [
      "./assets/Outside/unilorin dam.jpeg",
      "./assets/Outside/unilorin.dam.jpeg",
    ],
    location: "Unilorin",
  },
  {
    name: "Dolphin Resort Poll",
    type: "resort",
    images: [require("./assets/Outside/dolphin_resort.jpg")],
    imagesPath: ["./assets/Outside/dolphin_resort.jpg"],
    location: "",
  },
  {
    name: "Emirate Mall",
    type: "resort",
    images: [require("./assets/Outside/emirate.mall.jpeg")],
    imagesPath: ["./assets/Outside/emirate.mall.jpeg"],
    location: "",
  },
  {
    name: "Bolz Grillz",
    type: "restaurant",
    address: "Shop 32, Palm shopping mall, Fate Road, Ilorin",
    phone: "09017047156",
    email: "bolzchopsngrills@gmail.com",
    location: "Ilorin",
    images: [require("./assets/Outside/Bolz grillz.jpeg")],
    imagesPath: ["./assets/Outside/Bolz grillz.jpeg"],
  },
  { name: "Imoleboja", type: "" },
  {
    name: "Rustic Cheers",
    type: "",
    address: "Block 2, No 3, opp somewatt fresh hotel, Ilorin",
    phone: "09159923593",
    images: [
      require("./assets/Outside/rustic_cheers.jpg"),
      require("./assets/Outside/rustic_cheers_2.jpg"),
      require("./assets/Outside/rustic_cheers_3.jpg"),
    ],
    imagesPath: [
      "./assets/Outside/rustic_cheers.jpg",
      "./assets/Outside/rustic_cheers_2.jpg",
      "./assets/Outside/rustic_cheers_3.jpg",
    ],
    location: "Ilorin",
  },
  // {
  //   name: "Red Caffino",
  //   type: "lounge",
  //   address: "No 8b, Amuda Gobir Road, after Adewole Police Station",
  //   phone: "09121447125",
  //   images: [require("./assets/Outside/red_caffino.JPG")],
  //   imagesPath: ["./assets/Outside/red_caffino.JPG"],
  // },
  //   {
  //     name: "Fun City Family Park",
  //     type: "resort",
  //     images: [require("./assets/Outside/fun_city.JPG")]
  //     imagesPath: ["./assets/Outside/fun_city.JPG"],
  //   },
  // {
  //   name: "Number 8 Apartment",
  //   type: "lodge",
  //   location: "Ilorin",
  //   images: [
  //     require("./assets/Outside/n8.PNG"),
  //     require("./assets/Outside/n8_2.jpg"),
  //   ],
  //   imagesPath: ["./assets/Outside/n8.PNG", "./assets/Outside/n8_2.jpg"],
  // },
  {
    name: "Diamond Park",
    type: "resort",
    address:
      "Plot 2, New Yidi Rd, Irewolede, beside biliyam gas station, Oko Erin, 240101, Kwara.",
    workingHours: "8am - 7pm",
    phone: "07069144394",
    images: [require("./assets/Outside/diamond_park.jpeg")],
    imagesPath: ["./assets/Outside/diamond_park.jpeg"],
    location: "Oko Erin",
  },
  {
    name: "Sidney Pizzeria",
    type: "restaurant",
    address: "9 Catchment close,GRA,ilorin 240102,Kwara",
    phone: "08173985398",
    images: [require("./assets/Outside/sidney.jpg")],
    imagesPath: ["./assets/Outside/sidney.jpg"],
  },
  {
    name: "Obodo Restaurant",
    type: "restaurant",
    address: "255 Taiwo Road, Ilorin, 240281",
    workingHours: "11am - 10pm",
    phone: "07055758220",
    images: [require("./assets/Outside/obodo.jpg")],
    imagesPath: ["./assets/Outside/obodo.jpg"],
    location: "Ilorin",
  },
  // {
  //   name: "Obodo Lounge",
  //   type: "lounge",
  //   address: "255, Taiwo Road, Ilorin, 240281",
  //   workingHours: "11am - 12am",
  // },
  {
    name: "Cupid Lounge",
    type: "lounge",
    address: "40, Fate Rd, Oko Erin 240102, Kwara",
    images: [require("./assets/Outside/cupid_lounge.jpg")],
    imagesPath: ["./assets/Outside/cupid_lounge.jpg"],
    location: "Oko Erin",
  },
  {
    name: "Princess Tote",
    type: "",
  },
  {
    name: "Monday's Place",
    type: "lounge",
    address: "No 5, sunmonu abolarin street, flower garden GRA, Oko Erin",
    phone: "08090684110",
    images: [require("./assets/Outside/monday's_place.jpg")],
    imagesPath: ["./assets/Outside/monday's_place.jpg"],
  },
  {
    name: "Place Of Pleasure",
    type: "lounge",
    images: [require("./assets/Outside/place_of_pleasure.jpg")],
    imagesPath: ["./assets/Outside/place_of_pleasure.jpg"],
  },
  //   {
  //     name: "Unilorin Zoo",
  //     type: "resort",
  //     address: "University Road, Akambi-1v 240102, Kwara, Nigeria",
  //     workingHours: "8am - 6pm",
  //     images: [require("")]
  //   },
  // {
  //   name: "Oxygenation Lounge",
  //   type: "lounge",
  //   address: "Unar Audi Rd, Ilorin, 240212, Kwara.",
  //   phone: "08063450638",
  // },
  {
    name: "Club Rush",
    type: "",
    address:
      "Top Floor, Reo Cakes Buildingm Tanke Rd, Opposite Yakoyo Restaurant, Ilorin, 240212, Kwara",
    phone: "08063102925",
  },
  {
    name: "Klubb spartakuz",
    type: "",
    address: "Plot 31, Pipeline Road, Ilorin, Kwara State",
    phone: "09042861511",
  },
  {
    name: "Pricess Luxury Hotel",
    type: "lodge",
    address: "Plot 31, Pipeline Road, Ilorin, Kwara",
    phone: "09032499226",
    images: [require("./assets/Outside/princess hotel.jpeg")],
    imagesPath: ["./assets/Outside/princess hotel.jpeg"],
    location: "Ilorin",
  },
  {
    name: "Red Flame",
    address: "30, University Road, beside femtech, Tanke, Ilorin",
    phone: "08103975541",
    type: "",
    workingHours: "8am - 9pm",
    location: "Tanke,Ilorin",
  },
  {
    name: "The Place",
    type: "restaurant",
    address: "148 Umar Audi Road, GRA, Oko Erin 240102, Kwara",
    phone: "07041765290",
    images: [require("./assets/Outside/The place.jpeg")],
    imagesPath: ["./assets/Outside/The place.jpeg"],
  },
  {
    name: "T and K Restaurant",
    type: "restaurant",
    address: "60,University Road, Tanke, Ilorin, 240102, Kwara",
    phone: "08074515980",
    images: [require("./assets/Outside/T and K restaurant .jpeg")],
    imagesPath: ["./assets/Outside/T and K restaurant .jpeg"],
  },
  // {
  //   name: "Amala Place",
  //   type: "restaurant",
  //   address: "Fate Rd, Ilorin, 240102, Kwara",
  //   phone: "08168006272",
  //   images: [],
  //   imagesPath: []
  // },
  {
    name: "Pronto Restaurant",
    address: "Ilorin 240102, Kwara",
    phone: "09155577711",
    type: "restaurant",
    images: [require("./assets/Outside/pronto.jpg")],
    imagesPath: ["./assets/Outside/pronto.jpg"],
    location: "Ilorin",
  },
  {
    name: "BOA Foods",
    address: "",
    type: "restaurant",
    location: "Oke-Odo, Ilorin",
    images: [require("./assets/Outside/boa.jpeg")],
    imagesPath: ["./assets/Outside/boa.jpeg"],
  },
  {
    name: "G-Pinnacle Hotel",
    type: "lodge",
    images: [require("./assets/Outside/G_pinnacle.jpg")],
    imagesPath: ["./assets/Outside/G_pinnacle.jpg"],
  },
  {
    name: "Belmoris Hotel",
    type: "lodge",
    images: [require("./assets/Outside/belmoris.jpg")],
    imagesPath: ["./assets/Outside/belmoris.jpg"],
  },
];
